Document: wmstickynotes
Title: Debian wmstickynotes Manual
Author: <insert document author here>
Abstract: This manual describes what wmstickynotes is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/wmstickynotes/wmstickynotes.sgml.gz

Format: postscript
Files: /usr/share/doc/wmstickynotes/wmstickynotes.ps.gz

Format: text
Files: /usr/share/doc/wmstickynotes/wmstickynotes.text.gz

Format: HTML
Index: /usr/share/doc/wmstickynotes/html/index.html
Files: /usr/share/doc/wmstickynotes/html/*.html
